package com.example.weatherforecast.utils;

import androidx.annotation.NonNull;


import com.example.weatherforecast.R;

import java.util.HashMap;
import java.util.Map;

public class IconSelector {

    public static int getIcon(@NonNull String id) {
        switch (id) {
            case "100":
                return R.drawable._100;
            case "101":
                return R.drawable._101;
            case "102":
                return R.drawable._102;
            case "103":
                return R.drawable._103;
            case "104":
                return R.drawable._104;
            case "150":
                return R.drawable._150;
            case "151":
                return R.drawable._151;
            case "153":
                return R.drawable._153;
            case "154":
                return R.drawable._154;
            case "300":
                return R.drawable._300;
            case "301":
                return R.drawable._301;
            case "302":
                return R.drawable._302;
            case "303":
                return R.drawable._303;
            case "304":
                return R.drawable._304;
            case "305":
                return R.drawable._305;
            case "306":
                return R.drawable._306;
            case "307":
                return R.drawable._307;
            case "308":
                return R.drawable._308;
            case "309":
                return R.drawable._309;
            case "310":
                return R.drawable._310;
            case "311":
                return R.drawable._311;
            case "312":
                return R.drawable._312;
            case "313":
                return R.drawable._313;
            case "314":
                return R.drawable._314;
            case "315":
                return R.drawable._315;
            case "316":
                return R.drawable._316;
            case "317":
                return R.drawable._317;
            case "318":
                return R.drawable._318;
            case "350":
                return R.drawable._350;
            case "351":
                return R.drawable._351;
            case "399":
                return R.drawable._399;
            case "400":
                return R.drawable._400;
            case "401":
                return R.drawable._401;
            case "402":
                return R.drawable._402;
            case "403":
                return R.drawable._403;
            case "404":
                return R.drawable._404;
            case "405":
                return R.drawable._405;
            case "406":
                return R.drawable._406;
            case "407":
                return R.drawable._407;
            case "408":
                return R.drawable._408;
            case "409":
                return R.drawable._409;
            case "410":
                return R.drawable._410;
            case "456":
                return R.drawable._456;
            case "457":
                return R.drawable._457;
            case "499":
                return R.drawable._499;
            case "500":
                return R.drawable._500;
            case "501":
                return R.drawable._501;
            case "502":
                return R.drawable._502;
            case "503":
                return R.drawable._503;
            case "504":
                return R.drawable._504;
            case "507":
                return R.drawable._507;
            case "508":
                return R.drawable._508;
            case "509":
                return R.drawable._509;
            case "510":
                return R.drawable._510;
            case "511":
                return R.drawable._511;
            case "512":
                return R.drawable._512;
            case "513":
                return R.drawable._513;
            case "514":
                return R.drawable._514;
            case "515":
                return R.drawable._515;
            case "999":
                return R.drawable._999;
            case "901":
                return R.drawable._901;
            case "900":
                return R.drawable._900;

        }
        return 0;
    }
}
