package com.example.weatherforecast.database.bean;

public class DataBaseVariableNames {
    public static final String _ID = "_ID";
    public static final String DataBase_NAME = "weatherInformation.db";   //数据库的名字

    //城市表
    public static final String COLUMN_CITY_INFO_PROVINCE_NAME = "COLUMN_CITY_INFO_PROVINCE_NAME";
    public static final String COLUMN_CITY_INFO_CITY_NAME = "COLUMN_CITY_INFO_CITY_NAME";
    public static final String COLUMN_CITY_INFO_COUNTY_NAME = "COLUMN_CITY_INFO_COUNTY_NAME";


    //实时天气表：
    public static final String COLUMN_FORECAST_INFO_REALTIME_TEXT = "COLUMN_FORECAST_INFO_REALTIME_TEXT";
    public static final String COLUMN_FORECAST_INFO_REALTIME_TEMP = "COLUMN_FORECAST_INFO_REALTIME_TEMP";


    //三天天气预报
    //第一天
    public static final String COLUMN_FORECAST_INFO_1DAY_TIME = "COLUMN_FORECAST_INFO_1DAY_TIME";
    public static final String COLUMN_FORECAST_INFO_1DAY_ICON = "COLUMN_FORECAST_INFO_1DAY_ICON";
    public static final String COLUMN_FORECAST_INFO_1DAY_DESC = "COLUMN_FORECAST_INFO_1DAY_DESC";
    public static final String COLUMN_FORECAST_INFO_1DAY_TEMP_MAX = "COLUMN_FORECAST_INFO_1DAY_TEMP_MAX";
    public static final String COLUMN_FORECAST_INFO_1DAY_TEMP_MIN = "COLUMN_FORECAST_INFO_1DAY_TEMP_MIN";
    //第二天
    public static final String COLUMN_FORECAST_INFO_2DAY_TIME = "COLUMN_FORECAST_INFO_2DAY_TIME";
    public static final String COLUMN_FORECAST_INFO_2DAY_DESC = "COLUMN_FORECAST_INFO_2DAY_DESC";
    public static final String COLUMN_FORECAST_INFO_2DAY_ICON = "COLUMN_FORECAST_INFO_2DAY_ICON";
    public static final String COLUMN_FORECAST_INFO_2DAY_TEMP_MAX = "COLUMN_FORECAST_INFO_2DAY_TEMP_MAX";
    public static final String COLUMN_FORECAST_INFO_2DAY_TEMP_MIN = "COLUMN_FORECAST_INFO_2DAY_TEMP_MIN";
    //第三天
    public static final String COLUMN_FORECAST_INFO_3DAY_TIME = "COLUMN_FORECAST_INFO_3DAY_TIME";
    public static final String COLUMN_FORECAST_INFO_3DAY_ICON = "COLUMN_FORECAST_INFO_3DAY_ICON";
    public static final String COLUMN_FORECAST_INFO_3DAY_DESC = "COLUMN_FORECAST_INFO_3DAY_DESC";
    public static final String COLUMN_FORECAST_INFO_3DAY_TEMP_MAX = "COLUMN_FORECAST_INFO_3DAY_TEMP_MAX";
    public static final String COLUMN_FORECAST_INFO_3DAY_TEMP_MIN = "COLUMN_FORECAST_INFO_3DAY_TEMP_MIN";


    //实时空气
    public static final String COLUMN_WEATHER_INFO_AIR_NOW_PM2_5 = "COLUMN_WEATHER_INFO_AIR_NOW_PM2_5";
    public static final String COLUMN_WEATHER_INFO_AIR_NOW_LEVEL = "COLUMN_WEATHER_INFO_AIR_NOW_LEVEL";
    public static final String COLUMN_WEATHER_INFO_AIR_NOW_CATEGORY = "COLUMN_WEATHER_INFO_AIR_NOW_CATEGORY";


    //生活指数
    public static final String COLUMN_WEATHER_INFO_LIFE_CLOTHES = "COLUMN_WEATHER_INFO_LIFE_CLOTHES";
    public static final String COLUMN_WEATHER_INFO_LIFE_TRIP = "COLUMN_WEATHER_INFO_LIFE_TRIP";

    public static final String COLUMN_WEATHER_INFO_LIFE_SPI = "COLUMN_WEATHER_INFO_LIFE_SPI";
    public static final String COLUMN_WEATHER_INFO_LIFE_SPORT = "COLUMN_WEATHER_INFO_LIFE_SPORT";
    public static final String COLUMN_WEATHER_INFO_LIFE_CAR_WASH = "COLUMN_WEATHER_INFO_LIFE_CAR_WASH";
    public static final String COLUMN_WEATHER_INFO_LIFE_COMFORT = "COLUMN_WEATHER_INFO_LIFE_COMFORT";
    public static final String COLUMN_WEATHER_INFO_LIFE_FLOW = "COLUMN_WEATHER_INFO_LIFE_FLOW";


    //24hour预报
    public static final String COLUMN_FORECAST_INFO_HOUR_1_TIME = "COLUMN_FORECAST_INFO_HOUR_1_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_1_ICON = "COLUMN_FORECAST_INFO_HOUR_1_ICON";

    public static final String COLUMN_FORECAST_INFO_HOUR_1_TEMP = "COLUMN_FORECAST_INFO_HOUR_1_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_1_DESC = "COLUMN_FORECAST_INFO_HOUR_1_DESC";

    public static final String COLUMN_FORECAST_INFO_HOUR_2_TIME = "COLUMN_FORECAST_INFO_HOUR_2_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_2_ICON = "COLUMN_FORECAST_INFO_HOUR_2_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_2_TEMP = "COLUMN_FORECAST_INFO_HOUR_2_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_2_DESC = "COLUMN_FORECAST_INFO_HOUR_2_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_3_TIME = "COLUMN_FORECAST_INFO_HOUR_3_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_3_ICON = "COLUMN_FORECAST_INFO_HOUR_3_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_3_TEMP = "COLUMN_FORECAST_INFO_HOUR_3_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_3_DESC = "COLUMN_FORECAST_INFO_HOUR_3_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_4_TIME = "COLUMN_FORECAST_INFO_HOUR_4_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_4_ICON = "COLUMN_FORECAST_INFO_HOUR_4_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_4_TEMP = "COLUMN_FORECAST_INFO_HOUR_4_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_4_DESC = "COLUMN_FORECAST_INFO_HOUR_4_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_5_TIME = "COLUMN_FORECAST_INFO_HOUR_5_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_5_ICON = "COLUMN_FORECAST_INFO_HOUR_5_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_5_TEMP = "COLUMN_FORECAST_INFO_HOUR_5_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_5_DESC = "COLUMN_FORECAST_INFO_HOUR_5_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_6_TIME = "COLUMN_FORECAST_INFO_HOUR_6_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_6_ICON = "COLUMN_FORECAST_INFO_HOUR_6_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_6_TEMP = "COLUMN_FORECAST_INFO_HOUR_6_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_6_DESC = "COLUMN_FORECAST_INFO_HOUR_6_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_7_TIME = "COLUMN_FORECAST_INFO_HOUR_7_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_7_ICON = "COLUMN_FORECAST_INFO_HOUR_7_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_7_TEMP = "COLUMN_FORECAST_INFO_HOUR_7_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_7_DESC = "COLUMN_FORECAST_INFO_HOUR_7_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_8_TIME = "COLUMN_FORECAST_INFO_HOUR_8_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_8_ICON = "COLUMN_FORECAST_INFO_HOUR_8_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_8_TEMP = "COLUMN_FORECAST_INFO_HOUR_8_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_8_DESC = "COLUMN_FORECAST_INFO_HOUR_8_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_9_TIME = "COLUMN_FORECAST_INFO_HOUR_9_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_9_ICON = "COLUMN_FORECAST_INFO_HOUR_9_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_9_TEMP = "COLUMN_FORECAST_INFO_HOUR_9_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_9_DESC = "COLUMN_FORECAST_INFO_HOUR_9_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_10_TIME = "COLUMN_FORECAST_INFO_HOUR_10_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_10_ICON = "COLUMN_FORECAST_INFO_HOUR_10_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_10_TEMP = "COLUMN_FORECAST_INFO_HOUR_10_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_10_DESC = "COLUMN_FORECAST_INFO_HOUR_10_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_11_TIME = "COLUMN_FORECAST_INFO_HOUR_11_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_11_ICON = "COLUMN_FORECAST_INFO_HOUR_11_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_11_TEMP = "COLUMN_FORECAST_INFO_HOUR_11_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_11_DESC = "COLUMN_FORECAST_INFO_HOUR_11_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_12_TIME = "COLUMN_FORECAST_INFO_HOUR_12_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_12_ICON = "COLUMN_FORECAST_INFO_HOUR_12_ICON";

    public static final String COLUMN_FORECAST_INFO_HOUR_12_TEMP = "COLUMN_FORECAST_INFO_HOUR_12_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_12_DESC = "COLUMN_FORECAST_INFO_HOUR_12_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_13_TIME = "COLUMN_FORECAST_INFO_HOUR_13_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_13_ICON = "COLUMN_FORECAST_INFO_HOUR_13_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_13_TEMP = "COLUMN_FORECAST_INFO_HOUR_13_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_13_DESC = "COLUMN_FORECAST_INFO_HOUR_13_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_14_TIME = "COLUMN_FORECAST_INFO_HOUR_14_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_14_ICON = "COLUMN_FORECAST_INFO_HOUR_14_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_14_TEMP = "COLUMN_FORECAST_INFO_HOUR_14_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_14_DESC = "COLUMN_FORECAST_INFO_HOUR_14_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_15_TIME = "COLUMN_FORECAST_INFO_HOUR_15_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_15_ICON = "COLUMN_FORECAST_INFO_HOUR_15_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_15_TEMP = "COLUMN_FORECAST_INFO_HOUR_15_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_15_DESC = "COLUMN_FORECAST_INFO_HOUR_15_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_16_TIME = "COLUMN_FORECAST_INFO_HOUR_16_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_16_ICON = "COLUMN_FORECAST_INFO_HOUR_16_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_16_TEMP = "COLUMN_FORECAST_INFO_HOUR_16_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_16_DESC = "COLUMN_FORECAST_INFO_HOUR_16_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_17_TIME = "COLUMN_FORECAST_INFO_HOUR_17_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_17_ICON = "COLUMN_FORECAST_INFO_HOUR_17_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_17_TEMP = "COLUMN_FORECAST_INFO_HOUR_17_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_17_DESC = "COLUMN_FORECAST_INFO_HOUR_17_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_18_TIME = "COLUMN_FORECAST_INFO_HOUR_18_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_18_ICON = "COLUMN_FORECAST_INFO_HOUR_18_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_18_TEMP = "COLUMN_FORECAST_INFO_HOUR_18_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_18_DESC = "COLUMN_FORECAST_INFO_HOUR_18_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_19_TIME = "COLUMN_FORECAST_INFO_HOUR_19_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_19_ICON = "COLUMN_FORECAST_INFO_HOUR_19_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_19_TEMP = "COLUMN_FORECAST_INFO_HOUR_19_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_19_DESC = "COLUMN_FORECAST_INFO_HOUR_19_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_20_TIME = "COLUMN_FORECAST_INFO_HOUR_20_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_20_ICON = "COLUMN_FORECAST_INFO_HOUR_20_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_20_TEMP = "COLUMN_FORECAST_INFO_HOUR_20_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_20_DESC = "COLUMN_FORECAST_INFO_HOUR_20_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_21_TIME = "COLUMN_FORECAST_INFO_HOUR_21_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_21_ICON = "COLUMN_FORECAST_INFO_HOUR_21_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_21_TEMP = "COLUMN_FORECAST_INFO_HOUR_21_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_21_DESC = "COLUMN_FORECAST_INFO_HOUR_21_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_22_TIME = "COLUMN_FORECAST_INFO_HOUR_22_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_22_ICON = "COLUMN_FORECAST_INFO_HOUR_22_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_22_TEMP = "COLUMN_FORECAST_INFO_HOUR_22_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_22_DESC = "COLUMN_FORECAST_INFO_HOUR_22_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_23_TIME = "COLUMN_FORECAST_INFO_HOUR_23_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_23_ICON = "COLUMN_FORECAST_INFO_HOUR_23_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_23_TEMP = "COLUMN_FORECAST_INFO_HOUR_23_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_23_DESC = "COLUMN_FORECAST_INFO_HOUR_23_DESC";
    public static final String COLUMN_FORECAST_INFO_HOUR_24_TIME = "COLUMN_FORECAST_INFO_HOUR_24_TIME";
    public static final String COLUMN_FORECAST_INFO_HOUR_24_ICON = "COLUMN_FORECAST_INFO_HOUR_24_ICON";
    public static final String COLUMN_FORECAST_INFO_HOUR_24_TEMP = "COLUMN_FORECAST_INFO_HOUR_24_TEMP";
    public static final String COLUMN_FORECAST_INFO_HOUR_24_DESC = "COLUMN_FORECAST_INFO_HOUR_24_DESC";
}